export const OPEN_PROFILE = 'OPEN_PROFILE';
export const CLOSE_PROFILE = 'CLOSE_PROFILE';
export const OPEN_MODAL_RECORD = 'OPEN_MODAL_RECORD';
export const CLOSE_MODAL_RECORD = 'CLOSE_MODAL_RECORD';
export const ACTIVE_SLIDE = 'ACTIVE_SLIDE';
export const REQUEST_SHARED_LINK = 'REQUEST_SHARED_LINK';